Repository CMPUT301W23T07/catch-me-if-you-scan, pull requests merged in 2023-03, with the labels that each got.

#51 Added more documentation, and added request for storage permission
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  app/app/.idea/.gitignore
  app/app/.idea/gradle.xml
  app/app/.idea/misc.xml
  app/app/.idea/vcs.xml
  app/app/src/main/.idea/misc.xml
  app/app/src/main/.idea/modules.xml
  app/app/src/main/.idea/vcs.xml
  app/app/src/main/.idea/workspace.xml
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/PermissionDialog.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/PermissionManager.java
Labels: backend

#69 61 push monster main
  app/app/src/main/AndroidManifest.xml
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/MonsterTest.java
Labels: backend

#72 58 adding testing to main activity
  .idea/workspace.xml
  app/.idea/androidTestResultsUserPreferences.xml
  app/.idea/deploymentTargetDropDown.xml
  app/app/build.gradle
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/CaptureActTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/LeaderboardFragmentTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/LoginActivityTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/MainActivityTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/PermissionDialogTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/SubmissionActivityTest.java
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MainActivity.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/PermissionManager.java
  app/app/src/main/res/values/themes.xml
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/ExampleUnitTest.java
  app/build.gradle
Labels: backend

#75 Adding more comments to monster class and tests
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/Monster.java
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/MonsterTest.java
Labels: backend

#81 32 create api for monster
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/CaptureAct.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/Monster.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MonsterController.java
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/MonsterControllerTest.java
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/MonsterTest.java
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/UserTest.java
Labels: backend

#83 74 activity testings are missing enough tests
  app/app/build.gradle
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/LeaderboardFragmentTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/LoginActivityTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/MainActivityTest.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/LoginActivity.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MainActivity.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ScanningManager.java
  app/app/src/main/res/layout/fragment_leaderboard.xml
  app/app/src/main/res/layout/fragment_profile.xml
Labels: documentation, backend

#89 84 user controller
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/UserController.java
Labels: backend

#92 added extra fix for dependencies and layout duplicate ID
  app/.idea/androidTestResultsUserPreferences.xml
  app/.idea/deploymentTargetDropDown.xml
  app/app/build.gradle
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/CaptureActTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/LeaderboardFragmentTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/MainActivityTest.java
  app/app/src/main/res/layout/fragment_leaderboard.xml
Labels: bug, backend

#98 96 give monster environment photo
  app/.idea/androidTestResultsUserPreferences.xml
  app/.idea/deploymentTargetDropDown.xml
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/Monster.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MonsterController.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/SubmissionActivity.java
Labels: backend

#104 identifiy user, unique name, profile info, comments
  app/.idea/androidTestResultsUserPreferences.xml
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/LoginActivity.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ProfileFragment.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/UserController.java
  app/app/src/main/res/layout/fragment_leaderboard.xml
  app/app/src/main/res/layout/fragment_profile.xml
Labels: player, player profile, backend

#126 108 monster and user aggregations
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/Monster.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MonsterController.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ProfileFragment.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/SubmissionActivity.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/User.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/UserController.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ViewMonsterFragment.java
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/MonsterTest.java
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/UserTest.java
Labels: enhancement, player, game QR codes, searching, backend

#131 fixed issue where user fetch resulted in error
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MonsterController.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/UserController.java
Labels: bug, backend

#138 fixed issue with illegal hex value
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MonsterController.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/UserController.java
Labels: bug, backend

#140 108 monster and user aggregations
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/UserController.java
Labels: bug, backend

#139 Cannot create an illegal account now
  app/.idea/deploymentTargetDropDown.xml
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/LoginActivity.java
Labels: bug, backend

#150 148 refactor monster fragment
  .DS_Store
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ViewMonsterFragment.java
  app/app/src/main/res/layout/fragment_view_monster.xml
Labels: backend, front end

#159 refactored tests to use a mock user and static methods
  app/.idea/androidTestResultsUserPreferences.xml
  app/.idea/deploymentTargetDropDown.xml
  app/app/build.gradle
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/LoginActivityTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/SubmissionActivityTest.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ProfileFragment.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/SubmissionActivity.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/TestDetails.java
Labels: backend

#166 comment controller done
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/Comment.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/CommentController.java
Labels: enhancement, backend

#171 153 finishing profile fragment
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MainActivity.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/Monster.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MonsterListAdapter.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MonsterListfragmentAdapter.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MonsterProfileListFragment.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ProfileFragment.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/User.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/UserController.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ViewMonsterFragment.java
  app/app/src/main/res/drawable/baseline_account_circle_24.xml
  app/app/src/main/res/drawable/baseline_arrow_forward_24.xml
  app/app/src/main/res/drawable/monsters_profile_list_container.xml
  app/app/src/main/res/drawable/monsters_profile_list_monster_item.xml
  app/app/src/main/res/layout/fragment_monster_profile_list.xml
  app/app/src/main/res/layout/fragment_profile.xml
  app/app/src/main/res/layout/fragment_view_monster.xml
  app/app/src/main/res/layout/monster_list_customize.xml
  app/app/src/main/res/layout/monster_list_fragment_customization.xml
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/MonsterTest.java
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/UserTest.java
Labels: backend
