Repository CMPUT301W23T07/catch-me-if-you-scan, pull requests merged in 2023-04, with the labels that each got.

#198 186 UI design needs to be updated
  app/.idea/deploymentTargetDropDown.xml
  app/.idea/jarRepositories.xml
  app/.idea/misc.xml
  app/.idea/render.experimental.xml
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/LoginActivityTest.java
  app/app/src/androidTest/java/cmput/app/catch_me_if_you_scan/MainActivityMapTest.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ProfileFragment.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/SetFont.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/SubmissionActivity.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/TypefaceUtil.java
  app/app/src/main/res/drawable/blue_to_yellow.xml
  app/app/src/main/res/drawable/custom_button.xml
  app/app/src/main/res/drawable/frosted_effect.xml
  app/app/src/main/res/drawable/my_qr_summary_background.xml
  app/app/src/main/res/drawable/offset_circle.xml
  app/app/src/main/res/drawable/rounded_corner.xml
  app/app/src/main/res/font/alata.ttf
  app/app/src/main/res/layout/activity_login.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/layout/activity_profile.xml
  app/app/src/main/res/layout/activity_scanning.xml
  app/app/src/main/res/layout/activity_submission.xml
  app/app/src/main/res/layout/comment_content.xml
  app/app/src/main/res/layout/dialog_comment.xml
  app/app/src/main/res/layout/fragment_leaderboard.xml
  app/app/src/main/res/layout/fragment_map.xml
  app/app/src/main/res/layout/fragment_monster_profile_list.xml
  app/app/src/main/res/layout/fragment_profile.xml
  app/app/src/main/res/layout/fragment_view_monster.xml
  app/app/src/main/res/layout/leaderboard_list_item.xml
  app/app/src/main/res/layout/monster_list_customize.xml
  app/app/src/main/res/layout/monster_list_fragment_customization.xml
  app/app/src/main/res/values-night/themes.xml
  app/app/src/main/res/values/colors.xml
  app/app/src/main/res/values/preloaded_fonts.xml
  app/app/src/main/res/values/styles.xml
  app/app/src/main/res/values/themes.xml
Labels: enhancement, front end

#199 fixed ui for monster
  app/.idea/deploymentTargetDropDown.xml
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ViewMonsterFragment.java
  app/app/src/main/res/layout/fragment_view_monster.xml
Labels: bug, backend

#205 fixed more ui things
  app/app/src/main/res/drawable/frosted_effect.xml
  app/app/src/main/res/layout/activity_submission.xml
  app/app/src/main/res/layout/fragment_profile.xml
  app/app/src/main/res/layout/fragment_view_monster.xml
Labels: enhancement, front end

#206 profile ui update
  app/app/src/main/res/layout/fragment_profile.xml
Labels: enhancement, front end

#208 fixed: navbar now tracks layout
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MainActivity.java
Labels: bug, backend

#209 blur monster fragment
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/BlurPhoto.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ViewMonsterFragment.java
Labels: enhancement, front end

#219 218 track qr
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/MapFragment.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/Monster.java
  app/app/src/main/java/cmput/app/catch_me_if_you_scan/ViewMonsterFragment.java
  app/app/src/main/res/drawable/baseline_image_24.xml
  app/app/src/main/res/drawable/baseline_pin_drop_24.xml
  app/app/src/main/res/layout/fragment_view_monster.xml
  app/app/src/test/java/cmput/app/catch_me_if_you_scan/MonsterTest.java
Labels: documentation, enhancement, backend
